### ISSUE TITLE
Signup with google plus, page redirection not working. 

### ISSUE THREAD

**Issue by AgriyaDev4** [agriya/getlancerv3-bidding#2]
**Describe the bug**
Signup with google plus, page redirection not working. 

**To Reproduce**
1. Go to signup.
2. Signup with Google plus.
3. Give the mail id and select the freelancer or employer.
4. After registered also, the page is not redirected.

**Expected behavior**
After registered a user, the page should be redirected to the dashboard

**Screenshots**
![page redirection](https://user-images.githubusercontent.com/44435120/47994885-adbbd400-e119-11e8-9e66-9ca9dc94293d.png)

**Comment by rrjanbiah** [comment]
Need clarification:

Is it happening when auto confirmation setting is enabled?
