### ISSUE TITLE
Email field asking email id after twitter registration

### ISSUE THREAD

**Issue by AgriyaDev4** [agriya/getlancerv3-bidding#3]
**Describe the bug**
After twitter registration we can log in via Twitter it's asking for email Id again, it can only asking while registration.  It should not ask Email id for login.

1. Go to 'Login'
2. Click on 'login with twitter'
3. After twitter registration we can log in via Twitter it's asking for email Id again, it can only asking while registration.  It should not ask Email id for login.

**Expected behavior**
After twitter registration we can log in via Twitter, it should directly login into the site. It should not ask email id for login.

**Screenshots**
![google plus](https://user-images.githubusercontent.com/4700341/48475228-5c4ecb80-e822-11e8-9ccd-7431e2b40215.png)

**Comment by rrjanbiah** [comment]
This is not an issue. 

As Twitter won't return email address, have to capture it in our website. This behavior can be seen in few other websites too.
