### ISSUE TITLE
Installation - You don't have permission to access /client/ on this server.

### ISSUE THREAD

**Issue by workforcecity** [agriya/getlancerv3-bidding#99]
Following instructions for Ubuntu + php 5.6 + Apache2 

Getting following message when try to access it.

Forbidden
You don't have permission to access /client/ on this server.

**Comment by rrjanbiah** [comment]
@workforcecity 

Thanks for posting this issue. But, this is related to your server setup. Hence, you may opt for commercial support at https://www.agriya.com/products/freelancer-clone
